// frontend/admin-portal/src/app/pages/create-job/create-job.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { CreateJobDto } from '../../models/job.model';

@Component({
  selector: 'app-create-job',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './create-job.component.html'
})
export class CreateJobComponent {
  error = signal<string | null>(null);
  isSubmitting = signal<boolean>(false);

  job: CreateJobDto = {
    title: '',
    company: '',
    location: '',
    country: '',
    city: '',
    workType: '',
    applyUrl: '',
    source: 'Manual',
    description: '',
    salaryRange: '',
    tags: ''
  };

  constructor(
    private apiService: ApiService,
    private router: Router
  ) {}

  onSubmit(): void {
    this.error.set(null);
    this.isSubmitting.set(true);

    const jobData: CreateJobDto = {
      title: this.job.title,
      company: this.job.company,
      applyUrl: this.job.applyUrl,
      source: 'Manual',
      location: this.job.location || undefined,
      country: this.job.country || undefined,
      city: this.job.city || undefined,
      workType: this.job.workType || undefined,
      description: this.job.description || undefined,
      salaryRange: this.job.salaryRange || undefined,
      tags: this.job.tags || undefined
    };

    this.apiService.createJob(jobData).subscribe({
      next: () => {
        this.router.navigate(['/jobs']);
      },
      error: (err) => {
        this.error.set(err.error?.message || 'Failed to create job');
        this.isSubmitting.set(false);
      }
    });
  }

  cancel(): void {
    this.router.navigate(['/jobs']);
  }
}

<div>
  <h1 class="text-3xl font-bold text-gray-800 mb-8">Add New Job</h1>

  @if (error()) {
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-6">
      {{ error() }}
    </div>
  }

  <form (ngSubmit)="onSubmit()" class="bg-white rounded-lg shadow p-6 max-w-2xl">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <div class="md:col-span-2">
        <label class="block text-sm font-medium text-gray-700 mb-1">
          Job Title <span class="text-red-500">*</span>
        </label>
        <input
          type="text"
          [(ngModel)]="job.title"
          name="title"
          required
          class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="e.g., Senior Software Engineer"
        />
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">
          Company <span class="text-red-500">*</span>
        </label>
        <input
          type="text"
          [(ngModel)]="job.company"
          name="company"
          required
          class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="e.g., TechCorp"
        />
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">
          Apply URL <span class="text-red-500">*</span>
        </label>
        <input
          type="url"
          [(ngModel)]="job.applyUrl"
          name="applyUrl"
          required
          class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="https://example.com/apply"
        />
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Country</label>
        <input
          type="text"
          [(ngModel)]="job.country"
          name="country"
          class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="e.g., Egypt"
        />
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">City</label>
        <input
          type="text"
          [(ngModel)]="job.city"
          name="city"
          class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="e.g., Cairo"
        />
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Location (Full)</label>
        <input
          type="text"
          [(ngModel)]="job.location"
          name="location"
          class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="e.g., Cairo, Egypt - Remote"
        />
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Work Type</label>
        <select
          [(ngModel)]="job.workType"
          name="workType"
          class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="">Select...</option>
          <option value="Remote">Remote</option>
          <option value="Hybrid">Hybrid</option>
          <option value="Onsite">Onsite</option>
        </select>
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Salary Range</label>
        <input
          type="text"
          [(ngModel)]="job.salaryRange"
          name="salaryRange"
          class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="e.g., $80,000 - $120,000"
        />
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Tags</label>
        <input
          type="text"
          [(ngModel)]="job.tags"
          name="tags"
          class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="e.g., react, nodejs, typescript"
        />
      </div>

      <div class="md:col-span-2">
        <label class="block text-sm font-medium text-gray-700 mb-1">Description</label>
        <textarea
          [(ngModel)]="job.description"
          name="description"
          rows="5"
          class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="Job description..."
        ></textarea>
      </div>
    </div>

    <div class="flex gap-4 mt-6">
      <button
        type="submit"
        [disabled]="isSubmitting()"
        class="bg-blue-500 hover:bg-blue-600 text-white px-6 py-2 rounded-lg transition-colors disabled:opacity-50"
      >
        {{ isSubmitting() ? 'Creating...' : 'Create Job' }}
      </button>
      <button
        type="button"
        (click)="cancel()"
        class="bg-gray-200 hover:bg-gray-300 text-gray-800 px-6 py-2 rounded-lg transition-colors"
      >
        Cancel
      </button>
    </div>
  </form>
</div>

// frontend/admin-portal/src/pages/CreateJob.tsx
import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { jobsApi } from '../services/api';
import { CreateJobDto } from '../types/job';

export default function CreateJob() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [error, setError] = useState<string | null>(null);

  const mutation = useMutation({
    mutationFn: jobsApi.createJob,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['jobs'] });
      queryClient.invalidateQueries({ queryKey: ['dashboard-stats'] });
      navigate('/jobs');
    },
    onError: (err: Error) => {
      setError(err.message || 'Failed to create job');
    },
  });

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError(null);
    
    const formData = new FormData(e.currentTarget);
    const job: CreateJobDto = {
      title: formData.get('title') as string,
      company: formData.get('company') as string,
      location: formData.get('location') as string || undefined,
      country: formData.get('country') as string || undefined,
      city: formData.get('city') as string || undefined,
      workType: formData.get('workType') as string || undefined,
      applyUrl: formData.get('applyUrl') as string,
      source: 'Manual',
      description: formData.get('description') as string || undefined,
      salaryRange: formData.get('salaryRange') as string || undefined,
      tags: formData.get('tags') as string || undefined,
    };

    mutation.mutate(job);
  };

  return (
    <div>
      <h1 className="text-3xl font-bold text-gray-800 mb-8">Add New Job</h1>

      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-6">
          {error}
        </div>
      )}

      <form onSubmit={handleSubmit} className="bg-white rounded-lg shadow p-6 max-w-2xl">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="md:col-span-2">
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Job Title <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              name="title"
              required
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="e.g., Senior Software Engineer"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Company <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              name="company"
              required
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="e.g., TechCorp"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Apply URL <span className="text-red-500">*</span>
            </label>
            <input
              type="url"
              name="applyUrl"
              required
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="https://example.com/apply"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Country</label>
            <input
              type="text"
              name="country"
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="e.g., Egypt"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">City</label>
            <input
              type="text"
              name="city"
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="e.g., Cairo"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Location (Full)</label>
            <input
              type="text"
              name="location"
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="e.g., Cairo, Egypt - Remote"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Work Type</label>
            <select
              name="workType"
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="">Select...</option>
              <option value="Remote">Remote</option>
              <option value="Hybrid">Hybrid</option>
              <option value="Onsite">Onsite</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Salary Range</label>
            <input
              type="text"
              name="salaryRange"
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="e.g., $80,000 - $120,000"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Tags</label>
            <input
              type="text"
              name="tags"
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="e.g., react, nodejs, typescript"
            />
          </div>

          <div className="md:col-span-2">
            <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
            <textarea
              name="description"
              rows={5}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Job description..."
            />
          </div>
        </div>

        <div className="flex gap-4 mt-6">
          <button
            type="submit"
            disabled={mutation.isPending}
            className="bg-blue-500 hover:bg-blue-600 text-white px-6 py-2 rounded-lg transition-colors disabled:opacity-50"
          >
            {mutation.isPending ? 'Creating...' : 'Create Job'}
          </button>
          <button
            type="button"
            onClick={() => navigate('/jobs')}
            className="bg-gray-200 hover:bg-gray-300 text-gray-800 px-6 py-2 rounded-lg transition-colors"
          >
            Cancel
          </button>
        </div>
      </form>
    </div>
  );
}
