// frontend/admin-portal/src/app/pages/dashboard/dashboard.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../../services/api.service';
import { DashboardStats } from '../../models/job.model';

interface StatCard {
  title: string;
  value: number;
  icon: string;
  color: string;
}

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './dashboard.component.html'
})
export class DashboardComponent implements OnInit {
  stats = signal<DashboardStats | null>(null);
  isLoading = signal<boolean>(true);
  error = signal<string | null>(null);

  constructor(private apiService: ApiService) {}

  ngOnInit(): void {
    this.loadStats();
  }

  loadStats(): void {
    this.apiService.getDashboardStats().subscribe({
      next: (data) => {
        this.stats.set(data);
        this.isLoading.set(false);
      },
      error: (err) => {
        this.error.set('Error loading dashboard stats. Make sure the API is running.');
        this.isLoading.set(false);
      }
    });
  }

  getStatCards(): StatCard[] {
    const s = this.stats();
    if (!s) return [];
    
    return [
      { title: 'Total Jobs', value: s.totalJobs, icon: '💼', color: 'bg-blue-500' },
      { title: 'Active Jobs', value: s.activeJobs, icon: '✅', color: 'bg-green-500' },
      { title: 'Visible to Users', value: s.visibleJobs, icon: '👁️', color: 'bg-emerald-500' },
      { title: 'Hidden from Users', value: s.hiddenJobs, icon: '🙈', color: 'bg-orange-500' },
      { title: 'Manual Entries', value: s.manualEntries, icon: '✍️', color: 'bg-purple-500' },
      { title: 'Added Today', value: s.jobsAddedToday, icon: '📅', color: 'bg-pink-500' },
    ];
  }

  getJobsByCountry(): [string, number][] {
    const s = this.stats();
    if (!s?.jobsByCountry) return [];
    return Object.entries(s.jobsByCountry).sort((a, b) => b[1] - a[1]);
  }

  getJobsByWorkType(): [string, number][] {
    const s = this.stats();
    if (!s?.jobsByWorkType) return [];
    return Object.entries(s.jobsByWorkType).sort((a, b) => b[1] - a[1]);
  }

  getJobsBySource(): [string, number][] {
    const s = this.stats();
    if (!s?.jobsBySource) return [];
    return Object.entries(s.jobsBySource).sort((a, b) => b[1] - a[1]);
  }
}

@if (isLoading()) {
  <div class="flex items-center justify-center h-64">
    <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
  </div>
} @else if (error()) {
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
    {{ error() }}
  </div>
} @else {
  <div>
    <div class="flex justify-between items-center mb-8">
      <h1 class="text-3xl font-bold text-gray-800">Dashboard</h1>
    </div>

    <!-- Stats Cards -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4 mb-8">
      @for (card of getStatCards(); track card.title) {
        <div class="bg-white rounded-lg shadow p-4">
          <div class="flex items-center justify-between">
            <div>
              <p class="text-gray-500 text-xs">{{ card.title }}</p>
              <p class="text-2xl font-bold text-gray-800">{{ card.value }}</p>
            </div>
            <div [class]="card.color + ' p-2 rounded-full text-white text-xl'">
              {{ card.icon }}
            </div>
          </div>
        </div>
      }
    </div>

    <!-- Charts Row -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <div class="bg-white rounded-lg shadow p-6">
        <h3 class="text-lg font-semibold mb-4">Jobs by Country</h3>
        <div class="space-y-2 max-h-64 overflow-y-auto">
          @for (item of getJobsByCountry(); track item[0]) {
            <div class="flex justify-between items-center">
              <span class="text-gray-600">{{ item[0] }}</span>
              <span class="bg-blue-100 text-blue-800 px-2 py-1 rounded text-sm">{{ item[1] }}</span>
            </div>
          } @empty {
            <p class="text-gray-500">No data available</p>
          }
        </div>
      </div>

      <div class="bg-white rounded-lg shadow p-6">
        <h3 class="text-lg font-semibold mb-4">Jobs by Work Type</h3>
        <div class="space-y-2 max-h-64 overflow-y-auto">
          @for (item of getJobsByWorkType(); track item[0]) {
            <div class="flex justify-between items-center">
              <span class="text-gray-600">{{ item[0] }}</span>
              <span class="bg-green-100 text-green-800 px-2 py-1 rounded text-sm">{{ item[1] }}</span>
            </div>
          } @empty {
            <p class="text-gray-500">No data available</p>
          }
        </div>
      </div>

      <div class="bg-white rounded-lg shadow p-6">
        <h3 class="text-lg font-semibold mb-4">Jobs by Source</h3>
        <div class="space-y-2 max-h-64 overflow-y-auto">
          @for (item of getJobsBySource(); track item[0]) {
            <div class="flex justify-between items-center">
              <span class="text-gray-600">{{ item[0] }}</span>
              <span class="bg-purple-100 text-purple-800 px-2 py-1 rounded text-sm">{{ item[1] }}</span>
            </div>
          } @empty {
            <p class="text-gray-500">No data available</p>
          }
        </div>
      </div>
    </div>
  </div>
}

// frontend/admin-portal/src/pages/Dashboard.tsx
import { useQuery } from '@tanstack/react-query';
import { dashboardApi } from '../services/api';

export default function Dashboard() {
  const { data: stats, isLoading, error } = useQuery({
    queryKey: ['dashboard-stats'],
    queryFn: dashboardApi.getStats,
  });

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
        Error loading dashboard stats. Make sure the API is running.
      </div>
    );
  }

  return (
    <div>
      <div className="flex justify-between items-center mb-8">
        <h1 className="text-3xl font-bold text-gray-800">Dashboard</h1>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4 mb-8">
        <StatCard
          title="Total Jobs"
          value={stats?.totalJobs || 0}
          icon="💼"
          color="bg-blue-500"
        />
        <StatCard
          title="Active Jobs"
          value={stats?.activeJobs || 0}
          icon="✅"
          color="bg-green-500"
        />
        <StatCard
          title="Visible to Users"
          value={stats?.visibleJobs || 0}
          icon="👁️"
          color="bg-emerald-500"
        />
        <StatCard
          title="Hidden from Users"
          value={stats?.hiddenJobs || 0}
          icon="🙈"
          color="bg-orange-500"
        />
        <StatCard
          title="Manual Entries"
          value={stats?.manualEntries || 0}
          icon="✍️"
          color="bg-purple-500"
        />
        <StatCard
          title="Added Today"
          value={stats?.jobsAddedToday || 0}
          icon="📅"
          color="bg-pink-500"
        />
      </div>

      {/* Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="bg-white rounded-lg shadow p-6">
          <h3 className="text-lg font-semibold mb-4">Jobs by Country</h3>
          <div className="space-y-2 max-h-64 overflow-y-auto">
            {stats?.jobsByCountry && Object.entries(stats.jobsByCountry)
              .sort((a, b) => b[1] - a[1])
              .map(([country, count]) => (
              <div key={country} className="flex justify-between items-center">
                <span className="text-gray-600">{country}</span>
                <span className="bg-blue-100 text-blue-800 px-2 py-1 rounded text-sm">{count}</span>
              </div>
            ))}
            {(!stats?.jobsByCountry || Object.keys(stats.jobsByCountry).length === 0) && (
              <p className="text-gray-500">No data available</p>
            )}
          </div>
        </div>

        <div className="bg-white rounded-lg shadow p-6">
          <h3 className="text-lg font-semibold mb-4">Jobs by Work Type</h3>
          <div className="space-y-2 max-h-64 overflow-y-auto">
            {stats?.jobsByWorkType && Object.entries(stats.jobsByWorkType)
              .sort((a, b) => b[1] - a[1])
              .map(([type, count]) => (
              <div key={type} className="flex justify-between items-center">
                <span className="text-gray-600">{type}</span>
                <span className="bg-green-100 text-green-800 px-2 py-1 rounded text-sm">{count}</span>
              </div>
            ))}
            {(!stats?.jobsByWorkType || Object.keys(stats.jobsByWorkType).length === 0) && (
              <p className="text-gray-500">No data available</p>
            )}
          </div>
        </div>

        <div className="bg-white rounded-lg shadow p-6">
          <h3 className="text-lg font-semibold mb-4">Jobs by Source</h3>
          <div className="space-y-2 max-h-64 overflow-y-auto">
            {stats?.jobsBySource && Object.entries(stats.jobsBySource)
              .sort((a, b) => b[1] - a[1])
              .map(([source, count]) => (
              <div key={source} className="flex justify-between items-center">
                <span className="text-gray-600">{source}</span>
                <span className="bg-purple-100 text-purple-800 px-2 py-1 rounded text-sm">{count}</span>
              </div>
            ))}
            {(!stats?.jobsBySource || Object.keys(stats.jobsBySource).length === 0) && (
              <p className="text-gray-500">No data available</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function StatCard({ title, value, icon, color }: { title: string; value: number; icon: string; color: string }) {
  return (
    <div className="bg-white rounded-lg shadow p-4">
      <div className="flex items-center justify-between">
        <div>
          <p className="text-gray-500 text-xs">{title}</p>
          <p className="text-2xl font-bold text-gray-800">{value}</p>
        </div>
        <div className={`${color} p-2 rounded-full text-white text-xl`}>
          {icon}
        </div>
      </div>
    </div>
  );
}
