// frontend/admin-portal/src/pages/EditJob.tsx
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { jobsApi } from '../services/api';
import { UpdateJobDto } from '../types/job';

export default function EditJob() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [error, setError] = useState<string | null>(null);

  const { data: job, isLoading } = useQuery({
    queryKey: ['job', id],
    queryFn: () => jobsApi.getJob(Number(id)),
    enabled: !!id,
  });

  const mutation = useMutation({
    mutationFn: (data: UpdateJobDto) => jobsApi.updateJob(Number(id), data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['jobs'] });
      queryClient.invalidateQueries({ queryKey: ['job', id] });
      queryClient.invalidateQueries({ queryKey: ['dashboard-stats'] });
      navigate('/jobs');
    },
    onError: (err: Error) => {
      setError(err.message || 'Failed to update job');
    },
  });

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError(null);
    
    const formData = new FormData(e.currentTarget);
    const updates: UpdateJobDto = {
      title: formData.get('title') as string,
      company: formData.get('company') as string,
      location: formData.get('location') as string || undefined,
      country: formData.get('country') as string || undefined,
      city: formData.get('city') as string || undefined,
      workType: formData.get('workType') as string || undefined,
      applyUrl: formData.get('applyUrl') as string,
      description: formData.get('description') as string || undefined,
      salaryRange: formData.get('salaryRange') as string || undefined,
      tags: formData.get('tags') as string || undefined,
      isActive: formData.get('isActive') === 'true',
    };

    mutation.mutate(updates);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
      </div>
    );
  }

  if (!job) {
    return (
      <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
        Job not found
      </div>
    );
  }

  return (
    <div>
      <h1 className="text-3xl font-bold text-gray-800 mb-8">Edit Job</h1>

      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-6">
          {error}
        </div>
      )}

      <form onSubmit={handleSubmit} className="bg-white rounded-lg shadow p-6 max-w-2xl">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="md:col-span-2">
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Job Title <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              name="title"
              required
              defaultValue={job.title}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Company <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              name="company"
              required
              defaultValue={job.company}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Apply URL <span className="text-red-500">*</span>
            </label>
            <input
              type="url"
              name="applyUrl"
              required
              defaultValue={job.applyUrl}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Country</label>
            <input
              type="text"
              name="country"
              defaultValue={job.country || ''}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">City</label>
            <input
              type="text"
              name="city"
              defaultValue={job.city || ''}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Location (Full)</label>
            <input
              type="text"
              name="location"
              defaultValue={job.location || ''}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Work Type</label>
            <select
              name="workType"
              defaultValue={job.workType || ''}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="">Select...</option>
              <option value="Remote">Remote</option>
              <option value="Hybrid">Hybrid</option>
              <option value="Onsite">Onsite</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Salary Range</label>
            <input
              type="text"
              name="salaryRange"
              defaultValue={job.salaryRange || ''}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Tags</label>
            <input
              type="text"
              name="tags"
              defaultValue={job.tags || ''}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Status</label>
            <select
              name="isActive"
              defaultValue={job.isActive.toString()}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="true">Active</option>
              <option value="false">Inactive</option>
            </select>
          </div>

          <div className="md:col-span-2">
            <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
            <textarea
              name="description"
              rows={5}
              defaultValue={job.description || ''}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
        </div>

        <div className="flex gap-4 mt-6">
          <button
            type="submit"
            disabled={mutation.isPending}
            className="bg-blue-500 hover:bg-blue-600 text-white px-6 py-2 rounded-lg transition-colors disabled:opacity-50"
          >
            {mutation.isPending ? 'Saving...' : 'Save Changes'}
          </button>
          <button
            type="button"
            onClick={() => navigate('/jobs')}
            className="bg-gray-200 hover:bg-gray-300 text-gray-800 px-6 py-2 rounded-lg transition-colors"
          >
            Cancel
          </button>
        </div>
      </form>
    </div>
  );
}

// frontend/admin-portal/src/app/pages/edit-job/edit-job.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { Job, UpdateJobDto } from '../../models/job.model';

@Component({
  selector: 'app-edit-job',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './edit-job.component.html'
})
export class EditJobComponent implements OnInit {
  error = signal<string | null>(null);
  isLoading = signal<boolean>(true);
  isSubmitting = signal<boolean>(false);
  job = signal<Job | null>(null);

  private jobId!: number;

  // Form model
  formData = {
    title: '',
    company: '',
    location: '',
    country: '',
    city: '',
    workType: '',
    applyUrl: '',
    description: '',
    salaryRange: '',
    tags: '',
    isActive: 'true'
  };

  constructor(
    private apiService: ApiService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.jobId = Number(this.route.snapshot.paramMap.get('id'));
    this.loadJob();
  }

  loadJob(): void {
    this.apiService.getJob(this.jobId).subscribe({
      next: (job) => {
        this.job.set(job);
        this.formData = {
          title: job.title,
          company: job.company,
          location: job.location || '',
          country: job.country || '',
          city: job.city || '',
          workType: job.workType || '',
          applyUrl: job.applyUrl,
          description: job.description || '',
          salaryRange: job.salaryRange || '',
          tags: job.tags || '',
          isActive: job.isActive.toString()
        };
        this.isLoading.set(false);
      },
      error: (err) => {
        this.error.set('Job not found');
        this.isLoading.set(false);
      }
    });
  }

  onSubmit(): void {
    this.error.set(null);
    this.isSubmitting.set(true);

    const updates: UpdateJobDto = {
      title: this.formData.title,
      company: this.formData.company,
      applyUrl: this.formData.applyUrl,
      location: this.formData.location || undefined,
      country: this.formData.country || undefined,
      city: this.formData.city || undefined,
      workType: this.formData.workType || undefined,
      description: this.formData.description || undefined,
      salaryRange: this.formData.salaryRange || undefined,
      tags: this.formData.tags || undefined,
      isActive: this.formData.isActive === 'true'
    };

    this.apiService.updateJob(this.jobId, updates).subscribe({
      next: () => {
        this.router.navigate(['/jobs']);
      },
      error: (err) => {
        this.error.set(err.error?.message || 'Failed to update job');
        this.isSubmitting.set(false);
      }
    });
  }

  cancel(): void {
    this.router.navigate(['/jobs']);
  }
}

@if (isLoading()) {
  <div class="flex items-center justify-center h-64">
    <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
  </div>
} @else if (!job()) {
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
    Job not found
  </div>
} @else {
  <div>
    <h1 class="text-3xl font-bold text-gray-800 mb-8">Edit Job</h1>

    @if (error()) {
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-6">
        {{ error() }}
      </div>
    }

    <form (ngSubmit)="onSubmit()" class="bg-white rounded-lg shadow p-6 max-w-2xl">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="md:col-span-2">
          <label class="block text-sm font-medium text-gray-700 mb-1">
            Job Title <span class="text-red-500">*</span>
          </label>
          <input
            type="text"
            [(ngModel)]="formData.title"
            name="title"
            required
            class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">
            Company <span class="text-red-500">*</span>
          </label>
          <input
            type="text"
            [(ngModel)]="formData.company"
            name="company"
            required
            class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">
            Apply URL <span class="text-red-500">*</span>
          </label>
          <input
            type="url"
            [(ngModel)]="formData.applyUrl"
            name="applyUrl"
            required
            class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Country</label>
          <input
            type="text"
            [(ngModel)]="formData.country"
            name="country"
            class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">City</label>
          <input
            type="text"
            [(ngModel)]="formData.city"
            name="city"
            class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Location (Full)</label>
          <input
            type="text"
            [(ngModel)]="formData.location"
            name="location"
            class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Work Type</label>
          <select
            [(ngModel)]="formData.workType"
            name="workType"
            class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="">Select...</option>
            <option value="Remote">Remote</option>
            <option value="Hybrid">Hybrid</option>
            <option value="Onsite">Onsite</option>
          </select>
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Salary Range</label>
          <input
            type="text"
            [(ngModel)]="formData.salaryRange"
            name="salaryRange"
            class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Tags</label>
          <input
            type="text"
            [(ngModel)]="formData.tags"
            name="tags"
            class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Status</label>
          <select
            [(ngModel)]="formData.isActive"
            name="isActive"
            class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="true">Active</option>
            <option value="false">Inactive</option>
          </select>
        </div>

        <div class="md:col-span-2">
          <label class="block text-sm font-medium text-gray-700 mb-1">Description</label>
          <textarea
            [(ngModel)]="formData.description"
            name="description"
            rows="5"
            class="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
          ></textarea>
        </div>
      </div>

      <div class="flex gap-4 mt-6">
        <button
          type="submit"
          [disabled]="isSubmitting()"
          class="bg-blue-500 hover:bg-blue-600 text-white px-6 py-2 rounded-lg transition-colors disabled:opacity-50"
        >
          {{ isSubmitting() ? 'Saving...' : 'Save Changes' }}
        </button>
        <button
          type="button"
          (click)="cancel()"
          class="bg-gray-200 hover:bg-gray-300 text-gray-800 px-6 py-2 rounded-lg transition-colors"
        >
          Cancel
        </button>
      </div>
    </form>
  </div>
}
