// frontend/admin-portal/src/app/components/layout/layout.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { AuthService } from '../../services/auth.service';

interface NavItem {
  path: string;
  label: string;
  icon: string;
  exact: boolean;
}

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive, RouterOutlet],
  templateUrl: './layout.component.html'
})
export class LayoutComponent {
  navItems: NavItem[] = [
    { path: '/', label: 'Dashboard', icon: '📊', exact: true },
    { path: '/jobs', label: 'Jobs', icon: '💼', exact: true },
    { path: '/jobs/create', label: 'Add Job', icon: '➕', exact: true },
    { path: '/filters', label: 'Filters & Fetch', icon: '🔧', exact: true },
  ];

  constructor(public authService: AuthService) {}

  logout(): void {
    this.authService.logout();
  }

  getUserInitial(): string {
    const user = this.authService.user();
    return user?.fullName?.charAt(0) || user?.username?.charAt(0) || 'A';
  }
}

<div class="min-h-screen bg-gray-100">
  <!-- Sidebar -->
  <aside class="fixed inset-y-0 left-0 w-64 bg-gray-900 text-white flex flex-col">
    <div class="p-6">
      <h1 class="text-xl font-bold">TechJobs Admin</h1>
    </div>
    <nav class="mt-6 flex-1">
      @for (item of navItems; track item.path) {
        <a
          [routerLink]="item.path"
          routerLinkActive="bg-gray-800 text-white border-l-4 border-blue-500"
          [routerLinkActiveOptions]="{ exact: item.exact }"
          class="flex items-center px-6 py-3 text-gray-300 hover:bg-gray-800 hover:text-white transition-colors"
        >
          <span class="mr-3">{{ item.icon }}</span>
          {{ item.label }}
        </a>
      }
    </nav>
    
    <!-- User Info & Logout -->
    <div class="p-4 border-t border-gray-700">
      <div class="flex items-center mb-3">
        <div class="w-10 h-10 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-bold">
          {{ getUserInitial() }}
        </div>
        <div class="ml-3 overflow-hidden">
          <p class="text-sm font-medium text-white truncate">{{ authService.user()?.fullName || authService.user()?.username }}</p>
          <p class="text-xs text-gray-400 truncate">{{ authService.user()?.email }}</p>
        </div>
      </div>
      <button
        (click)="logout()"
        class="w-full flex items-center justify-center px-4 py-2 bg-red-600/20 text-red-400 rounded-lg hover:bg-red-600/30 transition-colors"
      >
        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
        </svg>
        Logout
      </button>
    </div>
  </aside>

  <!-- Main Content -->
  <main class="ml-64 p-8">
    <router-outlet></router-outlet>
  </main>
</div>

// frontend/admin-portal/src/components/Layout.tsx
import { Link, Outlet, useLocation } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

const navItems = [
  { path: '/', label: 'Dashboard', icon: '📊' },
  { path: '/jobs', label: 'Jobs', icon: '💼' },
  { path: '/jobs/create', label: 'Add Job', icon: '➕' },
  { path: '/filters', label: 'Filters & Fetch', icon: '🔧' },
];

export default function Layout() {
  const location = useLocation();
  const { user, logout } = useAuth();

  return (
    <div className="min-h-screen bg-gray-100">
      {/* Sidebar */}
      <aside className="fixed inset-y-0 left-0 w-64 bg-gray-900 text-white flex flex-col">
        <div className="p-6">
          <h1 className="text-xl font-bold">TechJobs Admin</h1>
        </div>
        <nav className="mt-6 flex-1">
          {navItems.map((item) => (
            <Link
              key={item.path}
              to={item.path}
              className={`flex items-center px-6 py-3 text-gray-300 hover:bg-gray-800 hover:text-white transition-colors ${
                location.pathname === item.path ? 'bg-gray-800 text-white border-l-4 border-blue-500' : ''
              }`}
            >
              <span className="mr-3">{item.icon}</span>
              {item.label}
            </Link>
          ))}
        </nav>
        
        {/* User Info & Logout */}
        <div className="p-4 border-t border-gray-700">
          <div className="flex items-center mb-3">
            <div className="w-10 h-10 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-bold">
              {user?.fullName?.charAt(0) || user?.username?.charAt(0) || 'A'}
            </div>
            <div className="ml-3 overflow-hidden">
              <p className="text-sm font-medium text-white truncate">{user?.fullName || user?.username}</p>
              <p className="text-xs text-gray-400 truncate">{user?.email}</p>
            </div>
          </div>
          <button
            onClick={logout}
            className="w-full flex items-center justify-center px-4 py-2 bg-red-600/20 text-red-400 rounded-lg hover:bg-red-600/30 transition-colors"
          >
            <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
            </svg>
            Logout
          </button>
        </div>
      </aside>

      {/* Main Content */}
      <main className="ml-64 p-8">
        <Outlet />
      </main>
    </div>
  );
}
